### PR TITLE
Removed redundant variables, and prepared for test.

### PR DESCRIPTION
**Pull request by ravisharmaa**
Please review the PR and tell me if I need to amend something.

### CODE REVIEW

**Comment by Stokoe0990** [comment]
Hey man, thanks for the contribution.

I don't think I'll be merging this PR because I'd have preferred to have kept using the service classes through dependency injection as opposed to accessing static methods through the class the way you've done it.

If the factories had have been separate factory classes which can be called individually, I'd have merged those in.

Again, thanks for the contribution! If you switch back to dependency injection and separate the factories I'd be more than happy to merge as there are a few others things you've done which I actually like.

**Comment by ravisharmaa** [comment]
Thanks, I might be doing that soon, I am planning to segregate the factories, may today or so, when I get up and running with tests, I guess it has gone extremely complex with building activities. I am planning to contribute more soon! Cheers! Hope you like it! Please, keep providing feedback.

**Comment by ravisharmaa** [comment]
Hey, can you please tell me what the activity service is doing, I am having hard time to refactor it and write tests for it. Especially, these lines: 
Screenshot from 2019-10-16 16-30-43

**Comment by Stokoe0990** [comment]
> Hey, can you please tell me what the activity service is doing, I am having hard time to refactor it and write tests for it. Especially, these lines:
> Screenshot from 2019-10-16 16-30-43

https://github.com/Stokoe0990/wikivel/blob/master/app/Http/Controllers/Web/HomeController.php#L56

You can see in here that a single activity record is passed to the `buildActivityData` method.

If you didn't remove the comments, you might have had a better idea of what it's doing.
But essentially:

`$changedRecord = $recentActivity->subject_type::where('id', $recentActivity->subject_id)->first();`
Finds record matching the class and ID.

```php
if ($changedRecord) {
            $changeType = $recentActivity->description;

           // If `$changedRecord` is set here, that means the record still exists (Which means the type of action was NOT `'deleted'`) the changeType can just be used as it is...
        } else {
            // ...otherwise if we can't find that record, it must have been deleted. So we set the `$changeType` here.

            // The `$changedRecord` lines will json_decode that `Activity` record's `properties` attribute. 
            // Which is a stored version of the deleted record in this part of the `if...else` block.
            $changedRecord = (object) json_decode($recentActivity->properties)->attributes;
            $changeType = 'deleted';
        }
```

Find the user who changed the record.
```php
$changedBy = User::where('id', $recentActivity->causer_id)->first();
```

**Comment by ravisharmaa** [comment]
Thanks, I am refactoring this now, might submit another pr, with amended code! Have a great time, I am closing this PR.

**Pull request closed without merging**
